# Generated by Django 2.0.6 on 2018-07-16 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date of contact')),
            ],
        ),
        migrations.CreateModel(
            name='ItemCommonInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Item', max_length=100)),
                ('author', models.CharField(default='Cotev', max_length=30)),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True)),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date of news')),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SketchComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(default='Anonymous', max_length=100)),
                ('message', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date of comment')),
            ],
        ),
        migrations.CreateModel(
            name='StoryPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.IntegerField(default=0)),
                ('page_title', models.CharField(max_length=100)),
                ('page', models.ImageField(upload_to='pages/')),
            ],
        ),
        migrations.CreateModel(
            name='Sketch',
            fields=[
                ('itemcommoninfo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog.ItemCommonInfo')),
                ('sketch_image', models.ImageField(upload_to='sketches/')),
            ],
            bases=('blog.itemcommoninfo',),
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('itemcommoninfo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog.ItemCommonInfo')),
                ('cover_page', models.ImageField(upload_to='covers/')),
            ],
            bases=('blog.itemcommoninfo',),
        ),
        migrations.AddField(
            model_name='sketchcomment',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.ItemCommonInfo'),
        ),
        migrations.AddField(
            model_name='storypage',
            name='story',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Story'),
        ),
    ]
