# Generated by Django 2.0.6 on 2018-07-18 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_delete_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animation',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog.Item')),
                ('url', models.URLField()),
            ],
            options={
                'abstract': False,
            },
            bases=('blog.item',),
        ),
    ]
