# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-18 02:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20161218_0205'),
    ]

    operations = [
        migrations.AddField(
            model_name='storypage',
            name='pageTitle',
            field=models.CharField(default='title', max_length=30),
        ),
    ]
