# Generated by Django 2.0.6 on 2018-07-15 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_sketchcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='sketchcomment',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.ItemCommonInfo'),
        ),
    ]
