# Generated by Django 2.0.6 on 2018-07-15 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_sketchcomment_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sketch',
            fields=[
                ('itemcommoninfo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog.ItemCommonInfo')),
                ('sketch_image', models.ImageField(upload_to='sketches/')),
            ],
            bases=('blog.itemcommoninfo',),
        ),
    ]
