# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-15 13:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20161218_0227'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storypage',
            old_name='pageNumber',
            new_name='page_number',
        ),
        migrations.RenameField(
            model_name='storypage',
            old_name='pageTitle',
            new_name='page_title',
        ),
    ]
