# Generated by Django 2.0.6 on 2018-07-15 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_sketch'),
    ]

    operations = [
        migrations.AddField(
            model_name='sketch',
            name='item_type',
            field=models.CharField(default='Sketch', max_length=100),
        ),
    ]
