# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-22 12:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20170115_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='cover_page',
            field=models.ImageField(default='media/covers/child_and_beat_page_1.png', upload_to='covers/'),
            preserve_default=False,
        ),
    ]
