# Generated by Django 2.0.6 on 2018-07-15 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_sketch_item_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sketch',
            name='item_type',
        ),
    ]
