# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-23 19:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='auther',
            new_name='author',
        ),
    ]
