# Generated by Django 2.0.6 on 2018-07-16 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_remove_sketch_item_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='story',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
