# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-24 22:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20170123_1940'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(default='Anonymous', max_length=100)),
                ('message', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date of comment')),
            ],
        ),
        migrations.CreateModel(
            name='Sketch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('auther', models.CharField(max_length=30)),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date of sketch')),
                ('sketch', models.ImageField(upload_to='sketches/')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='sketch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Sketch'),
        ),
        migrations.AddField(
            model_name='comment',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Story'),
        ),
    ]
