# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-24 23:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20170124_2244'),
    ]

    operations = [
        migrations.RenameField(
            model_name='story',
            old_name='auther',
            new_name='author',
        ),
    ]
