# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-24 23:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20170124_2305'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sketch',
            old_name='auther',
            new_name='author',
        ),
    ]
