# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-25 18:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20170125_1824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentsketch',
            name='sketch',
        ),
        migrations.RemoveField(
            model_name='commentstory',
            name='story',
        ),
        migrations.DeleteModel(
            name='CommentSketch',
        ),
        migrations.DeleteModel(
            name='CommentStory',
        ),
    ]
