# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-14 21:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20170125_1835'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True)),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date of news')),
                ('message', models.TextField()),
            ],
        ),
    ]
