# Generated by Django 2.0.6 on 2018-06-18 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storypage',
            name='story',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Story'),
        ),
    ]
