# Generated by Django 2.0.6 on 2018-07-14 11:28

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20180618_1919'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='sketch',
            managers=[
                ('comment', django.db.models.manager.Manager()),
            ],
        ),
    ]
