# Generated by Django 2.0.6 on 2018-07-14 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20180714_1128'),
    ]

    operations = [
        migrations.CreateModel(
            name='SketchComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(default='Anonymous', max_length=100)),
                ('message', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date of comment')),
            ],
        ),
        migrations.AlterModelManagers(
            name='sketch',
            managers=[
            ],
        ),
    ]
