# Generated by Django 2.0.6 on 2018-07-14 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_auto_20180714_1455'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCommonInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=30)),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
            ],
        ),
        migrations.RemoveField(
            model_name='sketch',
            name='author',
        ),
        migrations.RemoveField(
            model_name='sketch',
            name='date',
        ),
        migrations.RemoveField(
            model_name='sketch',
            name='id',
        ),
        migrations.RemoveField(
            model_name='sketch',
            name='sketch',
        ),
        migrations.RemoveField(
            model_name='sketch',
            name='title',
        ),
        migrations.AddField(
            model_name='sketch',
            name='sketch_image',
            field=models.ImageField(null=True, upload_to='sketches/'),
        ),
        migrations.AddField(
            model_name='sketch',
            name='itemcommoninfo_ptr',
            field=models.OneToOneField(auto_created=True, default='null', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog.ItemCommonInfo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sketchcomment',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.ItemCommonInfo'),
        ),
    ]
