# Generated by Django 2.0.6 on 2018-07-14 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_auto_20180714_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sketch',
            name='sketch_image',
            field=models.ImageField(upload_to='sketches/'),
        ),
    ]
