# Generated by Django 2.0.6 on 2018-10-07 15:29

from django.db import migrations
from django.conf import settings
from django.apps import apps


def update_site_name(apps, schema_editor):
    SiteModel = apps.get_model('sites', 'Site')
    domain = 'cotev.pythonanywhere.com'

    SiteModel.objects.update_or_create(
        pk = settings.SITE_ID,
        domain = domain,
        name = 'Nuances project',
    )

class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_animation'),
    ]

    operations = [
        migrations.RunPython(update_site_name),
    ]
